In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split

full_data = pd.read_csv("/Users/arichter/Documents/GitHub/be-fair/aide/MyData/mydataset.csv", index_col=0)
full_data

,super_label,skin_tone,alternative_skin_tone,expert_opinion,label,image_name
0,inflammatory,2,2,NaN,non-neoplastic,image_1
1,inflammatory,4,5,NaN,non-neoplastic,image_2
2,malignant melanoma,2,1,NaN,malignant,image_3
3,inflammatory,2,1,NaN,non-neoplastic,image_4
4,inflammatory,2,3,NaN,non-neoplastic,image_5
...,...,...,...,...,...,...
16572,inflammatory,3,2,NaN,non-neoplastic,image_16573
16573,inflammatory,2,1,NaN,non-neoplastic,image_16574
16574,inflammatory,-1,4,NaN,non-neoplastic,image_16575
16575,inflammatory,2,1,NaN,non-neoplastic,image_16576
16576,inflammatory,1,1,NaN,non-neoplastic,image_16577

In [14]:
without_super_label = full_data.drop(columns="super_label")
without_super_label

,skin_tone,alternative_skin_tone,expert_opinion,label,image_name
0,2,2,NaN,non-neoplastic,image_1
1,4,5,NaN,non-neoplastic,image_2
2,2,1,NaN,malignant,image_3
3,2,1,NaN,non-neoplastic,image_4
4,2,3,NaN,non-neoplastic,image_5
...,...,...,...,...,...
16572,3,2,NaN,non-neoplastic,image_16573
16573,2,1,NaN,non-neoplastic,image_16574
16574,-1,4,NaN,non-neoplastic,image_16575
16575,2,1,NaN,non-neoplastic,image_16576
16576,1,1,NaN,non-neoplastic,image_16577

In [17]:
train, test = train_test_split(without_super_label, test_size=10, random_state=42)
train= train.reset_index(drop=True)
#test= test.reset_index(drop=True).drop(columns=["super_label", "skin_tone", "alternative_skin_tone", "expert_opinion", "label"])
test= test.reset_index(drop=True).drop(columns=["skin_tone", "alternative_skin_tone", "expert_opinion", "label"])

In [18]:
train.to_csv("/Users/arichter/Documents/GitHub/be-fair/mlzero/train.csv")
test.to_csv("/Users/arichter/Documents/GitHub/be-fair/mlzero/test.csv")